version: "3.8"

services:
  nodeapp:
    build: .
    ports:
      - ${PORT}:${PORT}
    networks:
      - net
    volumes:
      - applogs:/app/src/logs
    restart: always
    env_file:
      - .env
    depends_on:
      - postgresdb

  postgresdb:
    container_name: demo_postgres
    build: db/
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: "/db/data"
    ports:
      - ${PGPORT}:${PGPORT}
    networks:
      - net
    volumes:
      - dbdata:/app/db/data
    restart: always
    env_file:
      - .env
networks:
  net:
    driver: bridge
volumes:
  applogs:
  dbdata:
